export const projects = [
    {
        category: 'architecture',
        title: 'the-house-between-two-roofs',
        client: "Mr.Venugopal Kamath",
        location: "Mangalore, Karnataka",
        year: "2021",
        area: "8750 Sq. Ft.",
        snippet: "Indulge life at our exquisite residential villa, seamlessly blending Mangalorean tradition with contemporary design, infused with deconstructed architectural elements, rustic finishes with a touch of minimalism, thoughtfully crafted openings for abundant light and refreshing ventilation.",
        summary1: "Located in the heart of Mangalore, at a sloping terrain, the client wanted a home looking overlooking the site. The house is an amalgamation of local Mangalorean architectural features enhanced with modern sentiments. With an emphasis for large open spaces, the house was designed to feel the sea breeze and let in nature into the living spaces",
        summary2: "Since the family often had large dinners and get-togethers, an open plan was designed, adjusted to their specific requirements. Double heights were provided for common spaces to further enhance the sense of openness. Landscaped parts were spread across these areas to breathe life into them.",
        summary3: "The traditional roof was split up to make it more modern and it gave an opportunity to introduce openings for ample daylight. The sloping site gave a natural demarcation to the entire plot, provide ample front yard and backyard spaces.",
        heroImg: '/projects/architecture/03-the-house-between-two-roofs/01-hero.png',
        images: [
            { url: "/projects/architecture/03-the-house-between-two-roofs/02.jpg" },
            { url: "/projects/architecture/03-the-house-between-two-roofs/03.jpg" },
            { url: "/projects/architecture/03-the-house-between-two-roofs/04.jpg" },
            { url: "/projects/architecture/03-the-house-between-two-roofs/05.jpg" },
            { url: "/projects/architecture/03-the-house-between-two-roofs/06.jpg" },
            { url: "/projects/architecture/03-the-house-between-two-roofs/07.jpg" },
            { url: "/projects/architecture/03-the-house-between-two-roofs/08_GF.jpg" },
            { url: "/projects/architecture/03-the-house-between-two-roofs/09_FF.jpg" },
        ]
    },
    {
        category: 'architecture',
        title: 'by-the-shore',
        client: "Mrs.Raksha Shetty",
        location: "Surathkal, Karnataka",
        year: "2022",
        area: "2500 Sq. Ft.",
        snippet: "Unveil the perfect fusion of rustic minimalism and modern charm in this house by the Suratkal beach. Imbued with the timeless elegance of traditional Mangalore design, discover a coastal sanctuary that transcends ordinary living.",
        summary1: "With beautiful plot just adjacent to the beach, with great potential, the beach house project had a great scope for design. The client’s family, though living away for most of the year, wanted a cosy homely place to get together once a year, a space to socialise and reconnect with everyone.",
        summary2: "The plan focused on large open spaces, with added emphasis on double heights and a play on levels. Large openings were given all over as views and spatial experience was prioritised. Complaint with vaastu, we ensured all spaces opened up outside to further enhance the connection with the exterior and ultimately the beach.",
        summary3: "Modern minimal design style was opted for the exteriors, with more focus on rugged rough surfaces to bring in that earthy Mangalorean atmosphere. Vertical and horizontal planes cut through the massing to increase a sense of dynamic design. Large double heighted glazing is directed towards the beach, which is the focal point ultimately.  ",
        heroImg: "/projects/architecture/01-by-the-shore/01-hero.png",
        images: [
            { url: "/projects/architecture/01-by-the-shore/01.png" },
            { url: "/projects/architecture/01-by-the-shore/02.png" },
            { url: "/projects/architecture/01-by-the-shore/03.png" },
            { url: "/projects/architecture/01-by-the-shore/04.png" },
            { url: "/projects/architecture/01-by-the-shore/05.png" },
            { url: "/projects/architecture/01-by-the-shore/06.png" },
            { url: "/projects/architecture/01-by-the-shore/07.png" },
            { url: "/projects/architecture/01-by-the-shore/08_GF.jpg" },
            { url: "/projects/architecture/01-by-the-shore/09_FF.jpg" },
        ]
    },
    {
        category: 'architecture',
        title: 'ns-excelsa',
        client: "Northern Sky",
        location: "Mangalore, Karnataka",
        year: "2022",
        area: "3,80,000 Sq. Ft.",
        snippet: "Ascend to new heights of contemporary living in our iconic high-rise residential tower, Excelsa. Immerse yourself in thoughtfully crafted layouts, curated interiors, and meticulously designed spaces, where modern dynamism meets unrivalled sophistication.",
        summary1: "The client came to us with the expressive intent of making a new iconic landmark for Mangalore, and thus, as the name suggest, Excelsa strives to excel in its design. Towering at 38 stories, the high rise building is eye-catchy with its well-lit fins adorning the building façade.  With a neutral colour palette, it connects to Mangalore at its grass roots, yet the modern sleek design indicates at the age we live in. ",
        summary2: "The building has an earthy neutral palette which would be timeless for the years to come. The Entry gate is designed so that there is a build-up of anticipation and in cultivates a sense of grandeur. The Lobby and other common spaces we designed keeping the theme in mind, and with the idea of giving the occupants a sense of luxury without it gravitating towards ostentatious.  ",
        summary3: "",
        heroImg: "/projects/architecture/02-ns-excelsa/01.jpg",
        images: [
            { url: "/projects/architecture/02-ns-excelsa/01.jpg" },
            { url: "/projects/architecture/02-ns-excelsa/02.jpg" },
            { url: "/projects/architecture/02-ns-excelsa/03.jpg" },
            { url: "/projects/architecture/02-ns-excelsa/04.jpg" },
            { url: "/projects/architecture/02-ns-excelsa/05.jpg" },
            { url: "/projects/architecture/02-ns-excelsa/06.jpg" },
            { url: "/projects/architecture/02-ns-excelsa/07.jpg" },
            { url: "/projects/architecture/02-ns-excelsa/08.jpg" },
            { url: "/projects/architecture/02-ns-excelsa/09.jpg" },
        ]
    },
    {
        category: 'architecture',
        title: 'ns-attalea',
        client: "Northern Sky",
        location: "Mangalore, Karnataka",
        year: "2022",
        area: "58,000 Sq. Ft.",
        snippet: "Discover urban elegance at Attalea, where a charming brick wall facade harmonizes with lush tropical landscaping. Experience smartly designed unit floor layouts, green running planters, and concrete and metal facade highlights, complemented by a plethora of premium amenities.",
        summary1: "The building has a striking exterior with brick cladding and concrete finishes that exudes a timeless charm. The rich, earthy finishes of the building create a warm, inviting ambience, blending harmoniously with the surrounding landscapes and cityscapes. The further add a sense of serenity and elegance to the building.",
        summary2: "On the interior, we have tried to offer a perfect blend of contemporary design with natural aesthetics. Large balconies with large windows allow natural light to filter in, illuminating the spaces and filling it with warmth and life. Simple clean lines have been used to make the design everlasting. ",
        summary3: "Special attention was given to the landscaping, with running planters going around the building, contributing not only to the greenery but also the façade design. Vertical runners are used at appropriate spaces to provide privacy which increasing the natural aesthetics. This provides the residents with a refreshing retreat and a connection with nature, in the middle of the city, almost as if like a lush oasis in the bustling city centre.",
        heroImg: "/projects/architecture/04-ns-attalea/01-hero.png",
        images: [
            { url: "/projects/architecture/04-ns-attalea/01.jpg" },
            { url: "/projects/architecture/04-ns-attalea/02.jpg" },
            { url: "/projects/architecture/04-ns-attalea/03.png" },
            { url: "/projects/architecture/04-ns-attalea/04.png" },
            { url: "/projects/architecture/04-ns-attalea/05.png" },
            { url: "/projects/architecture/04-ns-attalea/06.png" },
            { url: "/projects/architecture/04-ns-attalea/07.jpg" },
            { url: "/projects/architecture/04-ns-attalea/08.jpg" },
            { url: "/projects/architecture/04-ns-attalea/09.jpg" },
        ]
    },
    {
        category: 'architecture',
        title: 'the-wall',
        client: "Northern Sky",
        location: "Mangalore, Karnataka",
        year: "2021",
        area: "2065 Sq. Ft.",
        snippet: "Step into a realm of contemporary allure at our residential house, where a sprawling laterite wall steals the spotlight. With architectural elements effortlessly dividing spaces, a muted neutral palette accentuates its captivating contrast.",
        summary2: "The ground floor was designed to attend to the parents where as the top floor was planned for the son and his future family. The staircase became the main element of interest as you enter the house, with an overlooking bridge adding to it. The double height right at the entrance further enhanced the experience. ",
        summary3: "A large wall cutting through it was added as a feature element to let the house stand out in its otherwise drab locality. A strong textural finish was proposed to contrast the white walls and the Mangalore tiled roof. ",
        heroImg: "/projects/architecture/05-the-wall/01-hero.png",
        images: [
            { url: "/projects/architecture/05-the-wall/01.png" },
            { url: "/projects/architecture/05-the-wall/02.png" },
            { url: "/projects/architecture/05-the-wall/03.png" },
            { url: "/projects/architecture/05-the-wall/04.png" },
            { url: "/projects/architecture/05-the-wall/05.png" },
            { url: "/projects/architecture/05-the-wall/06.png" },
            { url: "/projects/architecture/05-the-wall/07.png" },
            { url: "/projects/architecture/05-the-wall/08_GF.jpg" },
            { url: "/projects/architecture/05-the-wall/09_FF.jpg" },
        ]
    },
    {
        category: 'architecture',
        title: 'lines-around-a-box',
        client: "Mr.Venugopal Kamath",
        location: "Mangalore, Karnataka",
        year: "2021",
        area: "8750 Sq. Ft.",
        snippet: "Experience the epitome of innovative design at this cosy residential house, where demands and vaastu requirements converge flawlessly. The simple massing is elevated through elemental design highlights, resulting in a harmonious and captivating home for the client.",
        summary2: "Since the family often had large dinners and get-togethers, an open plan was designed, adjusted to their specific requirements. Double heights were provided for common spaces to further enhance the sense of openness. Landscaped parts were spread across these areas to breathe life into them. ",
        summary3: "The traditional roof was split up to make it more modern and it gave an opportunity to introduce openings for ample daylight. The sloping site gave a natural demarcation to the entire plot, provide ample front yard and backyard spaces. ",
        heroImg: "/projects/architecture/06-lines-around-a-box/00-hero.png",
        images: [
            { url: "/projects/architecture/06-lines-around-a-box/00.jpg" },
            { url: "/projects/architecture/06-lines-around-a-box/01.jpg" },
            { url: "/projects/architecture/06-lines-around-a-box/02.jpg" },
            { url: "/projects/architecture/06-lines-around-a-box/03.jpg" },
            { url: "/projects/architecture/06-lines-around-a-box/06.jpg" },
            { url: "/projects/architecture/06-lines-around-a-box/07.jpg" },
            { url: "/projects/architecture/06-lines-around-a-box/08.jpg" },
            { url: "/projects/architecture/06-lines-around-a-box/GF.jpg" },
            { url: "/projects/architecture/06-lines-around-a-box/FF.jpg" },
        ]
    },
    {
        category: 'interiors',
        title: 'lakshmi-nivas',
        client: "Mr.Ravindranath Rai",
        location: "Mangalore, Karnataka",
        year: "2020",
        area: "2900 Sq. Ft.",
        snippet: "Embark on a journey of refined indulgence with the interiors of Lakshminivas. Dark contrasts and lustrous brass highlights dance harmoniously amidst modern ornamentalisms, evoking a timeless narrative. Dynamic ambient lights accentuate diverse complementing textures, unveiling an opulent visual symphony within your space.",
        summary1: "The client came to us with an intention of having interiors which would make a statement and bring out the design, and thus we have used a conscious collaboration of textures, colours and finishes to fulfil this objective. The apartment came with long hallways, large spatial zones and high lintels and we have focus on these elements to enhance the space. Rich veneer, projected stone textures, dark laminates with generous brass highlights and ample ambient lighting is infused into the house, giving a feel of premium luxury.  ",
        summary2: "",
        summary3: "The varying beams were disguised with wooden false ceiling along the hallway, combined with bullet lights for that dramatic effect. Blue hues were used to contrast the otherwise neutral palette of the house, further enhanced by the rich wood tones. Shapes connected to the client’s vaastu was infused in, thus creating an aesthetic plush home suiting all the clients’ needs. ",
        heroImg: "/projects/interior/01-lakshminivas/01-hero.jpg",
        images: [
            { url: "/projects/interior/01-lakshminivas/01.jpg" },
            { url: "/projects/interior/01-lakshminivas/02.JPG" },
            { url: "/projects/interior/01-lakshminivas/03.JPG" },
            { url: "/projects/interior/01-lakshminivas/04.JPG" },
            { url: "/projects/interior/01-lakshminivas/05.JPG" },
            { url: "/projects/interior/01-lakshminivas/06.PNG" },
            { url: "/projects/interior/01-lakshminivas/07.PNG" },
        ]
    },
    {
        category: 'interiors',
        title: 'zeus-fitness',
        client: "Zeus Fitness",
        location: "Mangalore, Karnataka",
        year: "2022",
        area: "5050 Sq. Ft.",
        snippet: "Step into a realm of raw energy within Zeus’s interiors. Embrace the allure of bold darkness and the essence of brutalist minimalism, where striking red accents of light and captivating signage ignite your motivation to conquer new frontiers.",
        summary1: "Dynamic, adrenaline filled, dark, cool, sporty, powerful and timeless, these were the words passionately used by the client when describing the emotions he expects for his gym and they set a guide point for the design of Zeus fitness. With a dark overtone, red highlights and large mirrors and glazing, the space screams power and energy. With efficiency being a priority along with aesthetics, clean minimal neat lines were used as a primary design language.",
        summary2: "Lighting played an important role in bringing the space to life, with ceiling light elements used to segregate the space as well as compliment circulation. Bold graphics on brutalistic textures and materials further augmented the feel of the space. The large glazing looking over the city balanced out the theme and brought in a freshness to the space. ",
        summary3: "",
        heroImg: "/projects/interior/02-zeus/01-hero.png",
        images: [
            { url: "/projects/interior/02-zeus/01.JPG" },
            { url: "/projects/interior/02-zeus/02.JPG" },
            { url: "/projects/interior/02-zeus/03.JPG" },
            { url: "/projects/interior/02-zeus/04.JPG" },
            { url: "/projects/interior/02-zeus/05.JPG" },
            { url: "/projects/interior/02-zeus/06.JPG" },
            { url: "/projects/interior/02-zeus/07.JPG" },
        ]
    },
    {
        category: 'interiors',
        title: 'b201',
        client: "Mr.Narayana Hegde",
        location: "Bangalore, Karnataka",
        year: "2021",
        area: "1850 Sq. Ft.",
        snippet: "Unveil the epitome of refined elegance in our mid-range home's interiors. Experience the tactile allure of matte finishes, a serene neutral palette with subtle contrasts, earthy textures, teak furniture, floating details, and clean lines that create a harmonious sanctuary.",
        summary1: "Minimal and earthy, that was the general direction we used to design the house B201, which matched with what the client was looking for. Matte finishes diffused the warm lighting around the house, offset by grey textured wall highlights. The teak furniture further compliments the space, coupled with indoor plants or rich tropical hues. Ceilings were kept simple and expansive, directing the attention towards the wall and the furniture.",
        summary2: "Pastel greens were used to highlight the bedrooms, coupled with mahogany shades and large pieces of art. Simple light fixtures further accentuated the space, with highlights of brass and diffused warm glows. A floating Pooja wall feature with Kota stone tied up the space together, creating a serene and peaceful home for its users. ",
        summary3: "",
        heroImg: "/projects/interior/03-b201/01-hero.png",
        images: [
            { url: "/projects/interior/03-b201/01.jpeg" },
            { url: "/projects/interior/03-b201/02.jpeg" },
            { url: "/projects/interior/03-b201/03.jpeg" },
            { url: "/projects/interior/03-b201/04.jpeg" },
            { url: "/projects/interior/03-b201/05.JPG" },
            { url: "/projects/interior/03-b201/06.JPG" },
            { url: "/projects/interior/03-b201/07.JPG" },
        ]
    },
    {
        category: 'interiors',
        title: 'tails-of-the-city',
        client: "Mrs.Swathi Rohit",
        location: "Bangalore, Karnataka",
        year: "2021",
        area: "700 Sq. Ft.",
        snippet: "Step into a haven of pampering at Tails of the City, where clean minimal design embraces pastel highlights, light woods to create a warm, inviting ambience. Custom graphics, clean lines, and a serene atmosphere ensure a tranquil retreat for both pets and owners alike.",
        summary1: "A space for pets to have fun and feel at home while they get groomed, these were the words the client greeted us with and thus set the tone for the whole design process for Tails of the City. A chic, trendy, minimal cosy space where pets and pet lovers can feel at home. Taking this into consideration, we decided to go with lighter colours and woods, pastel greens being the contrasting highlights.",
        summary2: "The furniture was kept simple, to blend into the background as well as the lights, with the main counter kept minimal yet trendy. Custom wallpapers were designed to go along with our theme, and funky, eye catching elements were added to enhance the playfulness of the space. Overall the store was designed to have a perfect balance of minimalism and vibrancy, with an infusion of cosiness. ",
        summary3: "",
        heroImg: "/projects/interior/04-tails-of-the-city/01-hero.png",
        images: [
            { url: "/projects/interior/04-tails-of-the-city/01.jpg" },
            { url: "/projects/interior/04-tails-of-the-city/02.jpg" },
            { url: "/projects/interior/04-tails-of-the-city/03.jpg" },
            { url: "/projects/interior/04-tails-of-the-city/04.jpg" },
            { url: "/projects/interior/04-tails-of-the-city/05.jpg" },
            { url: "/projects/interior/04-tails-of-the-city/06.jpg" },
            { url: "/projects/interior/04-tails-of-the-city/07.jpg" },
        ]
    },
    {
        category: 'interiors',
        title: '401',
        client: "Miss.Apeksha Rai",
        location: "Mangalore, Karnataka",
        year: "2021",
        area: "1800 Sq. Ft.",
        snippet: "Step into a realm of comfort and elegance in this residence, where colors and textures intertwine in perfect harmony. The neutral palette, ambient lighting, and modular fittings create an aesthetically pleasing environment that exudes timeless elegance.",
        summary1: "One of our initial projects, we strived to provide well designed and timeless interiors for the client through this project. Materials were chosen carefully to complement each other and the design was kept simple and contemporary. Lighting was used to highlight the spaces, and simple neat lines were used as a driving design language. Neutral palettes were kept in place to keep the space adaptable and aesthetically pleasing",
        summary2: "",
        summary3: "",
        heroImg: "/projects/interior/05-apeksha-residence/01-hero.png",
        images: [
            { url: "/projects/interior/05-apeksha-residence/01.jpeg" },
            { url: "/projects/interior/05-apeksha-residence/02.jpeg" },
            { url: "/projects/interior/05-apeksha-residence/03.jpeg" },
            { url: "/projects/interior/05-apeksha-residence/04.jpeg" },
            { url: "/projects/interior/05-apeksha-residence/05.jpeg" },
            { url: "/projects/interior/05-apeksha-residence/06.jpeg" },
            { url: "/projects/interior/05-apeksha-residence/07.jpeg" },
        ]
    },
    {
        category: 'landscape',
        title: 'the-garden',
        client: "Mr.Rakshit Surya",
        location: "Mangalore, Karnataka ",
        year: "2021",
        area: "1200 Sq. Ft.",
        snippet: "Unveil serenity within our captivating terrace garden, where Zen elements harmonize with thoughtful level differences for spatial distinction. Vertical louvers create a play of light, while stepping stone pathways and white pebbled beds inspire tranquility amidst warm, inviting lighting",
        summary1: "From an empty, unused terrace which was the unofficial storehouse, to a tastefully designed terrace garden, Mr.Rakshit’s was fun and exciting project for us to work on. The client wanted a space to relax and spend time in the evenings with his friends, and with the advent of COVID, we were glad to create an oasis at the roof of his house. The use of white pebble beds with stepping stones added a bright, clean and visually appealing element to the space. We have used raised platforms to add interest and dimension to the space, combined with vertical louvers for privacy and shade, done in an aesthetic way.",
        summary2: "Ambient lighting has been infused into the space, with diffused coves under the platforms, concrete effect hanging pendants over the bar, and warm lights to light up the space and create that peaceful ambience in the evening. The roof was covered with a wood effect PVC ceiling to induce that warm cosy feeling, and the neutral palette further complimented the design language. With all these elements in mind, a beautiful and serene terrace garden was born, which will provide a respite from the hustle and bustle of daily life.",
        summary3: "",
        heroImg: "/projects/landscape/01-the-garden/01.jpg",
        images: [
            { url: "/projects/landscape/01-the-garden/01.jpg" },
            { url: "/projects/landscape/01-the-garden/02.jpg" },
            { url: "/projects/landscape/01-the-garden/03.jpg" },
            { url: "/projects/landscape/01-the-garden/04.jpg" },
            { url: "/projects/landscape/01-the-garden/05.jpg" },
            { url: "/projects/landscape/01-the-garden/06.jpg" },
            { url: "/projects/landscape/01-the-garden/07.jpg" },
        ]
    },
    {
        category: 'interiors',
        title: 'mudigere-mane',
        client: "Mr.Suraj D U",
        location: "Mudigere, Karnataka",
        year: "2022",
        area: "3950 Sq. Ft.",
        snippet: "Journey through time in this colonial bungalow perched atop a hill, where rich wood tones and brass highlights adorn matte grey finishes, accentuating intricate patterns. Experience the seamless blend of traditional design with a contemporary touch, complemented by rustic custom furniture and articulately detailed elements, creating timeless opulence.",
        summary1: "A colonial British Bungalow perched on top of a hill, overlooking into vast green valleys of coffee estate, the site was as bewitching as it was picturesque. Being about 100 years old, the house had massive 2’ thick walls, with the central roof reaching upto 30’ in height. The potential for design and interiors was so great that what started as a simple renovation turned into a complete redesign of the property. Giving rich colonial vibes with an infusion of local traditions and culture, we used this as our guideline to design the house. ",
        summary2: "Having the intention of preserving the architectural qualities of the house, we retained the exteriors as it is, polishing it up to make it look new and fresh. A lot of colonial design elements we used for interiors, peppered with patterns finishes and culturally rich highlights. Wood was a driving force, and generously used throughout. All the openings were further enlarged and and augmented with arches and panelling. Decorative columns with modern lines were added, turning a space into a home which you wouldn’t want to leave. ",
        summary3: "",
        heroImg: "/projects/interior/06-mudigere-mane/01-hero.png",
        images: [
            { url: "/projects/interior/06-mudigere-mane/01.png" },
            { url: "/projects/interior/06-mudigere-mane/02.png" },
            { url: "/projects/interior/06-mudigere-mane/03.png" },
            { url: "/projects/interior/06-mudigere-mane/04.png" },
            { url: "/projects/interior/06-mudigere-mane/05.png" },
            { url: "/projects/interior/06-mudigere-mane/06.png" },
            { url: "/projects/interior/06-mudigere-mane/07.png" },
        ]
    },
    {
        category: 'landscape',
        title: 'serenity-cremtoria',
        client: "Government of Karnataka",
        location: "Mangalore, Karnataka ",
        year: "2022",
        area: "45400 Sq. Ft.",
        snippet: "Enter a sanctuary of solace at our crematorium, where extensive landscaped pathways lead through lush tropical greenery, adorned with indigenous Mangalorean flora. Stepped planters, wooden pergolas, raised platforms with double-height roofs create a serene space for reflection and farewell.",
        summary1: "The redesign for an existing and aging crematorium in Mangalore was focused towards providing a space where ancient traditions and modern elements come together to create a serene and peaceful environment for loved ones to say their final goodbyes. As you enter the crematorium, you are greeted by lush, green landscapes and well-designed wide pathways that lead to various sections of the facility. Along the pathways, you’re shaded by wooden pergolas, providing comfort for the mourners.  ",
        summary2: "The architecture is a beautiful fusion of traditional Hindu design with modern construction techniques. The use of natural finishes and materials, such as stone and wood, adds to the peaceful and serene atmosphere of the space. The main guiding goal was to provide a sense of comfort and closure for the families during difficult times. ",
        summary3: "",
        heroImg: "/projects/landscape/03-serenity-cremetorium/01.jpg",
        images: [
            { url: "/projects/landscape/03-serenity-cremetorium/01.jpg" },
            { url: "/projects/landscape/03-serenity-cremetorium/02.jpg" },
            { url: "/projects/landscape/03-serenity-cremetorium/03.jpg" },
            { url: "/projects/landscape/03-serenity-cremetorium/04.jpg" },
            { url: "/projects/landscape/03-serenity-cremetorium/05.jpg" },
            { url: "/projects/landscape/03-serenity-cremetorium/06.jpg" },
            { url: "/projects/landscape/03-serenity-cremetorium/07.jpg" },
        ]
    },
    {
        category: 'landscape',
        title: 'the-veiled-garden',
        client: "Mr.Akshath Acharya",
        location: "Mangalore, Karnataka ",
        year: "2021",
        area: "1600 Sq. Ft.",
        snippet: "Embark on a sensory journey in our captivating terrace garden, with two levels cascading in harmony. Jaalis create mesmerizing light and shadow play, while natural rough finishes evoke an organic allure. Well-placed and thoughtfully designed planter boxes completes the space.",
        summary1: "Upon visiting the site, we noticed the two levels and the great potential it presented to the site. Double heighted spaces, jalis’ for the light and shadow effect and the ways to connect the two levels gave scope for exciting design solutions. The use of white pebble beds with stepping stones added a bright, clean and visually appealing element to the space. We have used raised platforms to add interest and dimension to the space, combined with vertical louvers for privacy and shade, done in an aesthetic way.  ",
        summary2: "The roof was covered with a wood effect PVC ceiling to induce that warm cosy feeling, and the neutral palette further complimented the design language. Ambient lighting has been infused into the space, with diffused coves under the platforms, concrete effect hanging pendants over the bar, and warm lights to light up the space and create that peaceful ambience in the evening. With all these elements in mind, a beautiful and serene terrace garden was born, which will provide a respite from the hustle and bustle of daily life.  ",
        summary3: "",
        heroImg: "/projects/landscape/02-akshath-terrace/01.png",
        images: [
            { url: "/projects/landscape/02-akshath-terrace/01.png" },
            { url: "/projects/landscape/02-akshath-terrace/02.png" },
            { url: "/projects/landscape/02-akshath-terrace/03.png" },
            { url: "/projects/landscape/02-akshath-terrace/04.png" },
            { url: "/projects/landscape/02-akshath-terrace/05.png" },
            { url: "/projects/landscape/02-akshath-terrace/06.png" },
            { url: "/projects/landscape/02-akshath-terrace/07.png" },
        ]
    },

]